name: Natura
main: io.mooshe.natura.MainPlugin
version: 1.3
commands:
  natura:
    description: Used to define setting values for Natura.
    usage: /natura <setting> <value>
    permission: natura.admin
